### ISSUE TITLE
Opinion paper: when is a repository "research software ready"?

### ISSUE THREAD

**Issue by poikilotherm** [softwarepub/project.software-metadata.pub#4]
Based on talk from DCM2022, we should write a paper about what criteria should be met to name a repository / repository software "research software ready".

This links to re3data metadata stating "code" or "software" support - what does that even mean?

Related, older material: https://wssspe.researchcomputing.org.uk/wp-content/uploads/2016/06/WSSSPE4_paper_20.pdf

**Comment by sdruskat** [comment]
Could be a Ten Simple Rules paper.
